name: Build & deploy

on:
  push:
    branches: [ prod, dev ]
jobs:
  build:
    runs-on: ubuntu-latest

    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Cache modules
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: S3 deploy & cloudfront invalidation for dev branch
        if: ${{ github.ref == 'refs/heads/dev' }}
        run: |
          aws s3 sync build/ s3://${{ secrets.AWS_DEV_S3_BUCKET_NAME }}
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DEV_CLOUDFRONT_DISTRIBUTION_ID }} --paths \/*
      - name: S3 deploy & cloudfront invalidation for prod branch
        if: ${{ github.ref == 'refs/heads/prod' }}
        run: |
          aws s3 sync build/ s3://${{ secrets.AWS_PROD_S3_BUCKET_NAME }}
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_PROD_CLOUDFRONT_DISTRIBUTION_ID }} --paths \/*
